package org.lowern1ght.burg;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.zip.DataFormatException;
import java.util.zip.Inflater;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Pins the empty5x5.snbt fixture that the @GameTest framework reads
 * at server startup. The fixture is generated by tools/generate_empty5x5.py
 * and must round-trip through zlib + NBT without losing the "5x5x1
 * minecraft:stone" shape the gametest depends on.
 */
class EmptyFixtureTest {

    @Test
    @DisplayName("empty5x5.snbt exists on the classpath and is a valid zlib stream")
    void fixtureIsValidSnbt() throws IOException, DataFormatException {
        byte[] data;
        try (InputStream in = EmptyFixtureTest.class
                .getResourceAsStream("/data/burg/structure/empty5x5.snbt")) {
            assertNotNull(in, "fixture must ship on the classpath");
            data = in.readAllBytes();
        }
        assertTrue(data.length > 4, "compressed fixture is suspiciously small");

        // NBT in 1.21.1 is zlib-compressed (raw deflate), not gzip.
        Inflater inflater = new Inflater();
        inflater.setInput(data);
        byte[] decoded = new byte[2048];
        int n = inflater.inflate(decoded);
        inflater.end();
        assertTrue(n > 0, "decompressed output is empty");

        // Root is a TAG_Compound (0x0A) with an empty name (0x0000).
        assertEquals(0x0A, decoded[0] & 0xFF, "root tag is not Compound");
        ByteBuffer nameLen = ByteBuffer.wrap(decoded, 1, 2)
                .order(ByteOrder.BIG_ENDIAN);
        assertEquals(0, nameLen.getShort(), "root compound name length is not 0");
    }

    @Test
    @DisplayName("empty5x5.snbt decoded size and end-marker count match the pinned generator")
    void fixtureShapeIsRight() throws IOException, DataFormatException {
        byte[] data;
        try (InputStream in = EmptyFixtureTest.class
                .getResourceAsStream("/data/burg/structure/empty5x5.snbt")) {
            data = in.readAllBytes();
        }
        Inflater inflater = new Inflater();
        inflater.setInput(data);
        byte[] decoded = new byte[4096];
        inflater.inflate(decoded);
        inflater.end();

        // 25 inner compounds (one per block) + 1 root compound = 26 TAG_End markers
        // (each Compound closes with a 0x00 byte). The byte-count check pins the
        // exact generator output so a generator regression is caught.
        assertEquals(159, data.length, "fixture bytes changed since this test was pinned");
        int ends = 0;
        for (byte b : decoded) {
            if ((b & 0xFF) == 0x00) ends++;
        }
        assertTrue(ends >= 26, "expected at least 26 TAG_End markers, got " + ends);
    }
}
