package org.lowern1ght.burg;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.zip.GZIPInputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Pins the {@code burggametests.empty5x5.nbt} fixture that the {@code @GameTest}
 * framework reads at server startup via
 * {@code new FileToIdConverter("structure", ".nbt").idToFile(...)} —
 * {@code data/burg/structure/burggametests.empty5x5.nbt}, gzip-compressed.
 *
 * <p>The structure name carries the lowercased test-class simple name
 * ({@code burgametests.}) prefix because NeoForge's GameTestRegistry
 * enables {@code prefixGameTestTemplate} by default (avoids template-name
 * collisions across mods).
 *
 * <p>The fixture is generated by {@code tools/generate_empty5x5.py} and
 * round-trips through gzip + NBT without losing the 5x5x1 minecraft:stone
 * platform shape the gametest depends on.
 */
class EmptyFixtureTest {

    /**
     * Re-decompress a gzip stream and return the raw NBT bytes. The Minecraft
     * side uses {@code NbtIo.readCompressed} which wraps a
     * {@code GZIPInputStream}, so the fixture must be gzip (not raw deflate /
     * not zlib).
     */
    private static byte[] gunzip(InputStream in) throws IOException {
        try (GZIPInputStream gzip = new GZIPInputStream(in);
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            gzip.transferTo(out);
            return out.toByteArray();
        }
    }

    @Test
    @DisplayName("burggametests.empty5x5.nbt exists on the classpath and is a gzip-compressed NBT stream")
    void fixtureIsValidGzippedNbt() throws IOException {
        byte[] data;
        try (InputStream in = EmptyFixtureTest.class
                .getResourceAsStream("/data/burg/structure/burggametests.empty5x5.nbt")) {
            assertNotNull(in, "fixture must ship on the classpath");
            data = in.readAllBytes();
        }
        assertTrue(data.length > 4, "compressed fixture is suspiciously small");

        // Gzip magic header is 1F 8B — Minecraft's NbtIo.readCompressed
        // wraps a GZIPInputStream and rejects anything that isn't gzip.
        assertEquals(0x1F, data[0] & 0xFF, "fixture is not gzip (missing 0x1F magic)");
        assertEquals(0x8B, data[1] & 0xFF, "fixture is not gzip (missing 0x8B magic)");

        byte[] decoded = gunzip(new ByteArrayInputStream(data));
        assertTrue(decoded.length > 0, "decompressed output is empty");

        // Root is a TAG_Compound (0x0A) with an empty name (0x0000).
        assertEquals(0x0A, decoded[0] & 0xFF, "root tag is not Compound");
        int nameLen = ByteBuffer.wrap(decoded, 1, 2).order(ByteOrder.BIG_ENDIAN).getShort();
        assertEquals(0, nameLen, "root compound name length is not 0");
    }

    @Test
    @DisplayName("burggametests.empty5x5.nbt decoded shape matches the pinned generator (5x5x1, 1 palette, 25 blocks)")
    void fixtureShapeIsRight() throws IOException {
        byte[] data;
        try (InputStream in = EmptyFixtureTest.class
                .getResourceAsStream("/data/burg/structure/burggametests.empty5x5.nbt")) {
            data = in.readAllBytes();
        }
        byte[] decoded = gunzip(new ByteArrayInputStream(data));

        // Sanity: file size pinned so a generator regression is caught.
        assertEquals(183, data.length, "fixture bytes changed since this test was pinned");

        // Count end markers (TAG_End = 0x00):
        //   1 root + 1 BlockState Compound (in palette) + 25 inner block
        //   Compounds = 27 TAG_End markers.
        int ends = 0;
        for (byte b : decoded) {
            if ((b & 0xFF) == 0x00) ends++;
        }
        assertTrue(ends >= 27, "expected at least 27 TAG_End markers, got " + ends);

        // 1 palette entry (TAG_Compound + BlockState NBT inside).
        // Walk the decoded bytes: the "palette" tag is a NAMED child of the
        // root Compound. The byte before the name-length uint16 is the
        // child's tag type (0x09 = TAG_List). After the name, the TAG_List
        // VALUE begins: an element-type byte (0x0A = Compound), then a
        // int32 count, then each entry.
        int paletteIdx = indexOfName(decoded, "palette");
        assertTrue(paletteIdx > 0, "palette tag not found");
        assertEquals(0x09, decoded[paletteIdx - 1] & 0xFF, "palette child tag is not TAG_List");
        int paletteValueStart = paletteIdx + 2 + 7; // length field + "palette"
        assertEquals(0x0A, decoded[paletteValueStart] & 0xFF, "palette element is not Compound");
        int paletteCount = ByteBuffer.wrap(decoded, paletteValueStart + 1, 4)
                .order(ByteOrder.BIG_ENDIAN).getInt();
        assertEquals(1, paletteCount, "expected exactly 1 palette entry (minecraft:stone)");

        int blocksIdx = indexOfName(decoded, "blocks");
        assertTrue(blocksIdx > 0, "blocks tag not found");
        assertEquals(0x09, decoded[blocksIdx - 1] & 0xFF, "blocks child tag is not TAG_List");
        int blocksValueStart = blocksIdx + 2 + 6; // length field + "blocks"
        assertEquals(0x0A, decoded[blocksValueStart] & 0xFF, "blocks element is not Compound");
        int blocksCount = ByteBuffer.wrap(decoded, blocksValueStart + 1, 4)
                .order(ByteOrder.BIG_ENDIAN).getInt();
        assertEquals(25, blocksCount, "expected exactly 25 block entries (5x5x1)");
    }

    /**
     * Find the offset of the first NBT name-encoding whose string equals
     * {@code target}. An NBT name is a uint16 length + utf-8 bytes. We
     * return the offset of the uint16 length field (so the caller can
     * peek at the preceding tag-type byte for diagnostics and compute the
     * start of the tag's value payload as {@code offset + 2 + nameLength}).
     */
    private static int indexOfName(byte[] nbt, String target) {
        byte[] needle = target.getBytes();
        for (int i = 0; i <= nbt.length - needle.length - 2; i++) {
            int len = ByteBuffer.wrap(nbt, i, 2).order(ByteOrder.BIG_ENDIAN).getShort() & 0xFFFF;
            if (len == needle.length && i + 2 + len <= nbt.length) {
                boolean match = true;
                for (int j = 0; j < len; j++) {
                    if (nbt[i + 2 + j] != needle[j]) {
                        match = false;
                        break;
                    }
                }
                if (match) return i;
            }
        }
        return -1;
    }
}
